repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.90.3
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
      - id: terraform_tfsec
  - repo: https://github.com/bridgecrewio/checkov
    rev: 3.2.269
    hooks:
      - id: checkov
        args: ["-d", "."]
  - repo: https://github.com/antonbabenko/pre-commit-opa
    rev: v1.2.1
    hooks:
      - id: opa_fmt
      - id: conftest
        args: ["-p", "compliance/conftest", "-d", "."]
